/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.testaskisi;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import static org.apache.jena.enhanced.BuiltinPersonalities.model;
import org.apache.jena.rdf.model.*;
import org.apache.jena.util.FileManager;
import org.apache.jena.util.iterator.ExtendedIterator;
/*
 *
 * @author Jimis
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        Tmodel = new javax.swing.JTextField();
        Tbrand = new javax.swing.JTextField();
        Tengine_size = new javax.swing.JTextField();
        Tcolor = new javax.swing.JTextField();
        Tfuel = new javax.swing.JTextField();
        Tnav = new javax.swing.JTextField();
        Tairbags = new javax.swing.JTextField();
        Tengine_type = new javax.swing.JTextField();
        Ttrans_type = new javax.swing.JTextField();
        Ttrans_system = new javax.swing.JTextField();
        Twin_hand = new javax.swing.JTextField();
        TSpeedometer = new javax.swing.JTextField();
        Tair_con = new javax.swing.JTextField();
        Save = new javax.swing.JButton();
        Jbrand = new javax.swing.JLabel();
        Jfuel = new javax.swing.JLabel();
        Jeng_size = new javax.swing.JLabel();
        Jcolor = new javax.swing.JLabel();
        Jnav = new javax.swing.JLabel();
        JairB = new javax.swing.JLabel();
        JairC = new javax.swing.JLabel();
        JModel = new javax.swing.JLabel();
        jEng_type = new javax.swing.JLabel();
        Jtran_type = new javax.swing.JLabel();
        Jtrans_sys = new javax.swing.JLabel();
        Jspeed = new javax.swing.JLabel();
        JwinHand = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        jmenuItem = new javax.swing.JMenu();
        LoadFile = new javax.swing.JMenuItem();
        Exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ergasia");
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(255, 102, 255));

        Tmodel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TmodelActionPerformed(evt);
            }
        });

        Tbrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TbrandActionPerformed(evt);
            }
        });

        Tengine_size.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tengine_sizeActionPerformed(evt);
            }
        });

        Tairbags.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TairbagsActionPerformed(evt);
            }
        });

        Tair_con.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tair_conActionPerformed(evt);
            }
        });

        Save.setText("SAVE RDF");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        Jbrand.setText("Brand");

        Jfuel.setText("Fuel Type");

        Jeng_size.setText("Engine Size");

        Jcolor.setText("Color");

        Jnav.setText("Navigation");

        JairB.setText("Airbags");

        JairC.setText("AirCondition");

        JModel.setText("Model");

        jEng_type.setText("Engine Type");

        Jtran_type.setText("Trans Type");

        Jtrans_sys.setText("Trans System");

        Jspeed.setText("Speedometer");

        JwinHand.setText("Window Handler");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(JairC, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Tair_con, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(JairB, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Tairbags, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(Jnav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(Tnav, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(Jcolor, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Tcolor, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(Jeng_size, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(Tengine_size, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(Jfuel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Tfuel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(Jbrand, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Tbrand, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addComponent(JModel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(Tmodel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addComponent(jEng_type, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Tengine_type, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addComponent(Jtran_type, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Ttrans_type, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addComponent(Jtrans_sys, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Ttrans_system, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addComponent(JwinHand, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Twin_hand, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addComponent(Jspeed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TSpeedometer, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Save, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tbrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tmodel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jbrand)
                    .addComponent(JModel))
                .addGap(26, 26, 26)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tfuel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tengine_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jfuel)
                    .addComponent(jEng_type))
                .addGap(26, 26, 26)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tengine_size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ttrans_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jeng_size)
                    .addComponent(Jtran_type))
                .addGap(26, 26, 26)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tcolor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ttrans_system, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jcolor)
                    .addComponent(Jtrans_sys))
                .addGap(26, 26, 26)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tnav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Twin_hand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jnav)
                    .addComponent(JwinHand))
                .addGap(26, 26, 26)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tairbags, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TSpeedometer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JairB)
                    .addComponent(Jspeed))
                .addGap(27, 27, 27)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tair_con, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Save)
                    .addComponent(JairC))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jmenuItem.setText("Actions");

        LoadFile.setText("Load from File");
        LoadFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadFileActionPerformed(evt);
            }
        });
        jmenuItem.add(LoadFile);

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jmenuItem.add(Exit);

        menu.add(jmenuItem);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:#
        Model m = ModelFactory.createDefaultModel();
        String nsA = "http://ergasia/Car_Specs#";
        Resource car = m.createResource(nsA + "Car");
        Property p_inside = m.createProperty(nsA + "hasInside");
        Property p_outside = m.createProperty(nsA + "hasOutside");
        Resource inside = m.createResource(nsA + "inside");
        Resource outside = m.createResource(nsA + "outside");
        Resource window_handler = m.createResource(nsA + "window_handler");
        Resource airbags = m.createResource(nsA + "airbags");
        Resource console = m.createResource(nsA + " console");
        Resource speedometer = m.createResource(nsA + "speedometer");
        Resource air_condition = m.createResource(nsA + "air-condition");
        Resource navigation = m.createResource(nsA + "navigation");
        Resource engine = m.createResource(nsA + "engine");
        Resource transmission_system = m.createResource(nsA + "transmission_system");
        Resource transmission_type = m.createResource(nsA + "transmission_type");
        Resource fuel_type = m.createResource(nsA + "fuel_type");
        Resource engine_size = m.createResource(nsA + "engine_size");
        Resource engine_type = m.createResource(nsA + "engine_type");
        Resource color = m.createResource(nsA + "color");
        Resource brand = m.createResource(nsA + "brand");
        Resource model = m.createResource(nsA + "model");
        m.add(car, p_inside, inside)
                .add(car, p_outside, outside)
                .add(inside, p_inside, window_handler)
                .add(inside, p_inside, airbags)
                .add(window_handler, p_inside, Twin_hand.getText())
                .add(airbags, p_inside, Tairbags.getText())
                .add(inside, p_inside, console)
                .add(console, p_inside, speedometer)
                .add(console, p_inside, air_condition)
                .add(console, p_inside, navigation)
                .add(speedometer, p_inside, TSpeedometer.getText())
                .add(air_condition, p_inside, Tair_con.getText())
                .add(navigation, p_inside, Tnav.getText())
                .add(outside, p_outside, brand)
                .add(outside, p_outside, model)
                .add(outside, p_outside, color)
                .add(brand, p_outside, Tbrand.getText())
                .add(model, p_outside, Tmodel.getText())
                .add(color, p_outside, Tcolor.getText())
                .add(outside, p_outside, engine)
                .add(engine, p_outside, fuel_type)
                .add(engine, p_outside, transmission_system)
                .add(engine, p_outside, transmission_type)
                .add(engine, p_outside, engine_size)
                .add(engine, p_outside, engine_type)
                .add(fuel_type, p_outside, Tfuel.getText())
                .add(transmission_type, p_outside, Ttrans_type.getText())
                .add(transmission_system, p_outside, Ttrans_system.getText())
                .add(engine_size, p_outside, Tengine_size.getText())
                .add(engine_type, p_outside, Tengine_type.getText());

        //System.out.println("# -- no special prefixes defined");
        //System.out.println("# -- nsA defined");
        //m.setNsPrefix( "nsA", nsA );
        //System.out.println("# -- nsA and cat defined");
        //m.setNsPrefix( "cat", nsB );
        //m.write(System.out);
        String fileName = "ergasia.rdf";
        FileWriter out=null;
        try {
            out = new FileWriter(fileName);
        } catch (IOException ex) {
            
        }
        try {
            m.write(out, "RDF/XML-ABBREV");
        }finally {
            try {
                out.close();
            } catch (IOException closeException) {
                // ignore
            }
        }
    }//GEN-LAST:event_SaveActionPerformed

    private void TbrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TbrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TbrandActionPerformed

    private void TmodelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TmodelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TmodelActionPerformed

    private void Tengine_sizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tengine_sizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tengine_sizeActionPerformed

    private void TairbagsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TairbagsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TairbagsActionPerformed

    private void Tair_conActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tair_conActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tair_conActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void LoadFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadFileActionPerformed
        // TODO add your handling code here:
        FileNameExtensionFilter fil = new FileNameExtensionFilter("Rdf Files", "rdf");
        JFileChooser fc = new JFileChooser(".");
        fc.setFileFilter(fil);
        File file = null;
        int returnVal = fc.showOpenDialog(LoadFile);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            file = fc.getSelectedFile();
            //System.out.println("lol");
        }
        Model model = ModelFactory.createDefaultModel();
        // use the FileManager to find the input file
        InputStream in = FileManager.get().open(fc.getSelectedFile().getName());
        if (in == null) {
            throw new IllegalArgumentException(
                    "File: " + fc.getSelectedFile().getName() + " not found");
        }
        // read the RDF/XML file
        model.read(in, null);
        StmtIterator iter = model.listStatements();
        int i=0;
        while (iter.hasNext()) {
            Statement stmt = iter.nextStatement();  // get next statement
            Resource subject = stmt.getSubject();     // get the subject
            Property predicate = stmt.getPredicate();   // get the predicate
            RDFNode object = stmt.getObject();      // get the object
            //System.out.print(subject.toString());
            //System.out.print(" " + predicate.toString() + " ");
            if (object instanceof Resource) {
                //System.out.print(object.toString());
            } else {
                // object is a literal
               //System.out.print("something value i="+i+" " + " \"" + object.toString() + "\"");
                switch (i){
                    case 0:
                        Ttrans_type.setText(object.toString());
                        break;
                    case 1:
                        Tbrand.setText(object.toString());
                        break;
                    case 2:
                        Tengine_type.setText(object.toString());
                        break;
                    case 3:
                        Tfuel.setText(object.toString());
                        break;
                    case 4:
                        Tairbags.setText(object.toString());
                        break;
                    case 5:
                        Tmodel.setText(object.toString());
                        break;
                    case 6:
                        Twin_hand.setText(object.toString());
                        break;
                    case 7:
                        Ttrans_system.setText(object.toString());
                        break;
                    case 8:
                        TSpeedometer.setText(object.toString());
                        break;
                    case 9:
                        Tnav.setText(object.toString());
                        break;
                    case 10:
                        Tcolor.setText(object.toString());
                        break;
                    case 11:
                        Tengine_size.setText(object.toString());
                        break;
                    case 12:
                        Tair_con.setText(object.toString());
                        break;                       
                }
                i++;
            }

            //System.out.println(" .");
        }

    }//GEN-LAST:event_LoadFileActionPerformed

    /**
     * @param args the command line arguments
     * @throws java.io.IOException
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Exit;
    private javax.swing.JLabel JModel;
    private javax.swing.JLabel JairB;
    private javax.swing.JLabel JairC;
    private javax.swing.JLabel Jbrand;
    private javax.swing.JLabel Jcolor;
    private javax.swing.JLabel Jeng_size;
    private javax.swing.JLabel Jfuel;
    private javax.swing.JLabel Jnav;
    private javax.swing.JLabel Jspeed;
    private javax.swing.JLabel Jtran_type;
    private javax.swing.JLabel Jtrans_sys;
    private javax.swing.JLabel JwinHand;
    private javax.swing.JMenuItem LoadFile;
    private javax.swing.JButton Save;
    protected static javax.swing.JTextField TSpeedometer;
    protected static javax.swing.JTextField Tair_con;
    protected static javax.swing.JTextField Tairbags;
    protected static javax.swing.JTextField Tbrand;
    protected static javax.swing.JTextField Tcolor;
    protected static javax.swing.JTextField Tengine_size;
    protected static javax.swing.JTextField Tengine_type;
    protected static javax.swing.JTextField Tfuel;
    protected static javax.swing.JTextField Tmodel;
    protected static javax.swing.JTextField Tnav;
    protected static javax.swing.JTextField Ttrans_system;
    protected static javax.swing.JTextField Ttrans_type;
    protected static javax.swing.JTextField Twin_hand;
    private javax.swing.JLabel jEng_type;
    private javax.swing.JMenu jmenuItem;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menu;
    // End of variables declaration//GEN-END:variables
}
